[buildPlans.IosevkaBaked]
family = "Iosevka Baked"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.IosevkaBaked.weights.Regular]
shape = 550
menu = 500
css = 500

[buildPlans.IosevkaBaked.weights.Bold]
shape = 750
menu = 700
css = 700

[buildPlans.IosevkaBaked.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaBaked.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaBaked.variants.design]
asterisk = "penta-low"
caret = "low"
at = "compact"
percent = "rings-continuous-slash"
# lig-hyphen-chain = "without-notch"
# lig-plus-chain = "without-notch"

[buildPlans.IosevkaBaked.ligations]
enables = ["trig",
"--default-kern--",
"--default-center-ops--",
# "--default-chaining--",
# "--fast-chaining--",
"html-comment",
"slash-asterisk",
"brst",
"llgg",
"llggeq",
"logic",
"ltgt-diamond-tag",
"ltgt-slash-tag",
]
